### PR TITLE
adjust XL Fortran OMP flag; fixes #232

### LINKED ISSUE #232: OpenMP flags for XL Fortran
Hans Jørgen Aa. Jensen informed me that IBM colleagues at the Summit workshop recommended to change `-qsmp` to `-qsmp=omp` in `CMAKE_Fortran_COMPILER_ID`. If you want to also enable the new OpenMP 4.5+ features to off-load to a GPU from OpenMP in XL Fortran, one should specify "-qsmp=omp -qoffload".

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by bast** [comment]
Can you please look over this @robertodr?

**Comment by bast** [comment]
Hmm. Yes, that would be even better. Thanks. One thing that starts to bother me a bit is the diffuse versioning in Autocmake but that is a separate issue. We need to think about it.

**Comment by bast** [comment]
One problem that I see with this is that FindOpenMP.cmake potentially pulls in other modules (I haven't tested this but see this happening with FindMPI.cmake. I think we should merge this since it's better than before but I think that offloading to FindOpenMP.cmake is not so trivial.

**Comment by robertodr** [comment]
Agreed that this is better than nothing.

**Pull request merged**
