### PR TITLE
Color module for CMake output

### PR DESCRIPTION
**Pull request by robertodr**
This module adds definitions to be used to colorize CMake output. Usage: 
```
message("${Red}This is Red${ColourReset}")
```
also documented in the module.
Code was found on StackOverflow: http://stackoverflow.com/a/19578320
Thanks also to @loriab

### CODE REVIEW

**Comment by bast** [comment]
How will this behave on WIN32?

**Comment by miroi** [comment]
I don't know since I haven't tested autocmake on MS Windows... If we want to know, we should add appveyor.yml CI buildup file...

**Comment by bast** [comment]
The test breakage is actually from my code change. I will fix that, sorry for that. We can test the colors with undefined variables. I think they default to "" but we should double check.

**Comment by bast** [comment]
Merged. Thanks! I will set it explicitly to "" on WIN32.

**Comment by bast** [comment]
See https://github.com/coderefinery/autocmake/commit/893c9bd80cd9ed1780c8a67dae5cda00eb9f722f.

**Pull request merged**
